---
title: "A Not so Simple Workflow"
author: "Simon Goring, Socorro Dominguez Vidana"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}
options(warn = -1)
suppressMessages(library(neotoma2))
suppressMessages(library(sf))
suppressMessages(library(geojsonsf))
suppressMessages(library(dplyr))
suppressMessages(library(ggplot2))
```



```{r getStara}
stara <- get_downloads(24238)
stara_chron <- chronologies(stara)

stara_chron %>% as.data.frame() %>% 
  DT::datatable(data = .)
```

There are three chronologies here.  We want to build a new one with `Bchron`:

```{r buildChronControl}
controls <- chroncontrols(stara) %>% 
  filter(chronologyid == 14591) %>% 
  arrange(depth)

controls$chroncontrolage[1] <- 0
controls$agelimityounger[1] <- -2
controls$thickness[1] <- 1

predictDepths <- samples(stara) %>%
  select(depth) %>% 
  unique() %>% 
  unlist()

newChron <- Bchron::Bchronology(ages = controls$chroncontrolage,
                                ageSds = abs(controls$agelimityounger - 
                                               controls$chroncontrolage),
                                calCurves = c("normal", rep("intcal20", 4)),
                                positionThicknesses = controls$thickness,
                                positions = controls$depth,
                                allowOutside = TRUE,
                                ids = controls$chroncontrolid)

plot(newChron) +
  ggplot2::labs(
    title = "Stará Boleslav",
    xlab = "Age (cal years BP)",
    ylab = "Depth (cm)"
  )

```

Now we want to add the chronology back to the record:

```{r}
set_chronology()
```
