install.packages("tidyverse")
install.packages("pacman")
install.packages("remotes")
install.packages('sf', type = 'source')
install.packages("geojsonsf")
install.packages("analogue")
install.packages("rioja")
install.packages("vegan")
install.packages("rbacon")
install.packages("leaflet")
install.packages("Bchron")
install.packages("DT")
install.packages("raster")
install.packages("terra")
#install.packages("neotoma2")

remotes::install_github('NeotomaDB/neotoma2@CRANv1.0.2b')
